package com.kraigochieng.embroideryis.server.models;

public enum Role {
    // ITEM PRIVILEGES
    CREATE_ITEM, READ_ITEM, UPDATE_ITEM, DELETE_ITEM,

    // POSITION PRIVILEGES
    CREATE_POSITION, READ_POSITION, UPDATE_POSITION, DELETE_POSITION,

    // COLOUR PRIVILEGES
    CREATE_COLOUR, READ_COLOUR, UPDATE_COLOUR, DELETE_COLOUR,

    // USER_PRIVILEGES
    CREATE_USER, READ_USER, UPDATE_USER, DELETE_USER,

    // ROLE_PRIVILEGES
    CREATE_ROLE, READ_ROLE, UPDATE_ROLE, DELETE_ROLE

}
