name: Trigger auto deployment for embroidery-is-v2-client

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'client/**'
    - '.github/workflows/embroidery-is-v2-client-AutoDeployTrigger-7488ff30-8103-4dbb-8fb5-b117b5623c4b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EMBROIDERYISV2CLIENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EMBROIDERYISV2CLIENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EMBROIDERYISV2CLIENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/client 
          registryUrl: docker.io
          registryUsername: ${{ secrets.EMBROIDERYISV2CLIENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EMBROIDERYISV2CLIENT_REGISTRY_PASSWORD }}
          containerAppName: embroidery-is-v2-client
          resourceGroup: embroidery-is-v2
          imageToBuild: kraigochieng/embroidery-is-v2-client:${{ github.sha }}
          dockerfilePath: Dockerfile


