name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push client
        working-directory: ./client
        run: |
          docker build -t kraigochieng/embroidery-is-v2-client:latest .
          docker push kraigochieng/embroidery-is-v2-client:latest

      - name: Build and push server
        working-directory: ./server
        run: |
          docker build -t kraigochieng/embroidery-is-v2-server:latest .
          docker push kraigochieng/embroidery-is-v2-server:latest
