name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push client
        working-directory: ./client
        run: |
          docker build -t kraigochieng/embroidery-is-v2-client:latest .
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          docker push kraigochieng/embroidery-is-v2-client:latest
